name: 'Conventional PR Action'
description: 'Check if PR title follows conventional commit format. Optionally adds label to PR that corresponds to the type of the commit.'
author: 'Yaroslav Buhaiev'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  allowed-types:
    description: 'Allowed types of commits. Specified as a JSON array of strings.'
    required: false
    default: '["feat", "fix", "docs", "style", "refactor", "perf", "test", "build", "ci", "chore", "revert", "dependencies"]'

runs:
  using: node20
  main: dist/index.js
