name: 'Conventional PR Action'
description: 'Check if PR title follows conventional commit format. Optionally adds label to PR that corresponds to the type of the commit.'
author: 'Yaroslav Buhaiev'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  githubToken:
    description: 'GitHub API token. Default token is used by default'
    required: false
    default: '${{ github.token }}'

  allowedTypes: |
    feat
    fix

# ignoreIfLabeledWith: |
#   skip-conventional-pr-action

# Define your outputs here.
# outputs:
#   time:
#     description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
